CREATE TYPE "OwnershipType" AS ENUM ('MARKETPLACE', 'SELF_OPERATED');

ALTER TABLE "Shop"
ADD COLUMN "ownershipType" "OwnershipType" NOT NULL DEFAULT 'MARKETPLACE';

ALTER TABLE "Product"
ADD COLUMN "costPrice" DECIMAL(10, 2);

ALTER TABLE "OrderItem"
ADD COLUMN "costPriceSnapshot" DECIMAL(10, 2);
