CREATE TYPE "OrderStatus_new" AS ENUM (
  'VERIFYING',
  'PROCESSING',
  'SHIPPED',
  'RECEIVED',
  'CANCELLED'
);

ALTER TABLE "Order"
ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "Order"
ALTER COLUMN "status" TYPE "OrderStatus_new"
USING (
  CASE "status"::text
    WHEN 'PENDING' THEN 'VERIFYING'
    WHEN 'CONFIRMED' THEN 'VERIFYING'
    WHEN 'PROCESSING' THEN 'PROCESSING'
    WHEN 'DONE' THEN 'SHIPPED'
    WHEN 'CANCELLED' THEN 'CANCELLED'
    ELSE 'VERIFYING'
  END
)::"OrderStatus_new";

ALTER TABLE "Order"
ALTER COLUMN "status" SET DEFAULT 'VERIFYING';

DROP TYPE "OrderStatus";

ALTER TYPE "OrderStatus_new" RENAME TO "OrderStatus";
